name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install shiroa-cli from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: shiroa-cli
          git: https://github.com/Myriad-Dreamin/shiroa

      - name: Install "Crimson Pro"
        uses: SnO2WMaN/install-fontsource-action@v0.0.2
        with:
          font-name: Crimson Pro

      - name: Install "Julia Mono"
        uses: SnO2WMaN/install-juliamono-action@v0.0.1

      - name: Print tools version
        run: |
          shiroa --version

      - name: Build Book
        run: shiroa build --path-to-root /shiroa-playground/

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
